py_binary(
    name = "export_kicad",
    srcs = ["export_kicad.py"],
    deps = [
        "//cpu:format_py_proto",
        "@abseil-py//absl/flags",
        "@abseil-py//absl:app",
        "@pip_deps//skidl",
        "@pip_deps//graphviz",
    ]
)
